module.exports = [
  {
    name: "Bombparty",
    description:
      "Jeu multijoueur où chaque participant doit trouver un mot contenant une suite de lettres prédéfinie.",
    type: "Application Web",
    url: "http://www.bombparty.nicolas.guerroudj.fr",
    src: "//github.com/NicolasGdj/Bombparty",
    image: "bombparty.png",
    year: 2020,
    tags: ["NodeJS", "Socket IO"],
  },
  {
    name: "MyLimits",
    description: "Carte de la France présentant la limitation de 100 km autour de sa position.",
    type: "Application Web",
    url: "http://mylimits.nicolas.guerroudj.fr",
    src: "//github.com/NicolasGdj/MyLimits",
    image: "mylimits.png",
    year: 2020,
    tags: ["NodeJS", "Google API"],
  },
  {
    name: "DrawIt",
    description:
      "Jeu multijoueur où chaque participant doit trouver le mot dessiné par un autre participant.",
    type: "Application Web",
    url: "http://drawit.nicolas.guerroudj.fr",
    src: "//github.com/NicolasGdj/drawit",
    image: "drawit.png",
    year: 2020,
    tags: ["NodeJS", "Socket IO"],
  },
  {
    name: "GladOS",
    description: "Système d'exploitation dont le shell est inspiré de Glados du jeu Portal",
    type: "Système d'exploitation",
    url: "https://www.youtube.com/watch?v=RgJ948pzJxw",
    src: "//github.com/NicolasGdj/GladOS",
    buttons: {
      see: "Vidéo",
    },
    image: "glados.png",
    year: 2022,
    tags: ["C"],
  },
  {
    name: "TwoNotes",
    description: "Application mobile permettant la prise de note collaborative",
    type: "Application Mobile",
    url: "https://www.youtube.com/watch?v=Y7Bk75WKeDg",
    src: "//github.com/NicolasGdj/TwoNotes",
    buttons: {
      see: "Vidéo",
    },
    image: "twonotes.png",
    year: 2022,
    tags: ["React Native"],
  },
  {
    name: "CV",
    description:
      "Le site web sur lequel vous vous trouvez actuellement, présentant mon curriculum vitae ainsi que mes projets personnels.",
    type: "Application Web",
    url: "#index",
    src: "//github.com/NicolasGdj/CV",
    image: "cv.png",
    year: 2023,
    tags: ["NodeJS", "EJS"],
  },
  {
    name: "Chromalight",
    description:
      "Un jeu de puzzle basé sur les lasers, où les joueurs doivent dévier les rayons à l'aide de miroirs pour résoudre les enigmes.",
    type: "Jeu",
    url: "https://nicolasgdj.github.io/Chromalight/WebGL/",
    src: "//github.com/NicolasGdj/Chromalight/",
    image: "chromalight.png",
    year: 2023,
    tags: ["C#", "Unity"],
  },
  {
    name: "Folina - CVE-2022-30190",
    description:
      "Démonstration de l'exploitation de la CVE-2022-30190, plus connu sous le nom de 'Folina', dans un environnement contrôlé.",
    type: "Securité",
    url: "https://www.youtube.com/watch?v=4MQwFDLHrnw",
    src: "/assets/projects/follina.pdf",
    buttons: {
      see: "Vidéo",
      source: "Rapport",
    },
    image: "follina.jpg",
    year: 2023,
    tags: ["Vagrant", "VirtualBox", "CVE"],
  },
  {
    name: "Jenkins - CVE-2022-43407",
    description:
      "Démonstration de l'exploitation de la CVE-2022-43407: une CSRF sur le plugin Jenkins 'Pipeline: Step Input'.",
    type: "Securité",
    url: "https://www.youtube.com/watch?v=rqX6ExYomxk",
    src: "/assets/projects/cve-jenkins.pdf",
    buttons: {
      see: "Vidéo",
      source: "Rapport",
    },
    image: "cve-jenkins.jpg",
    year: 2023,
    tags: ["Docker", "Jenkins", "CVE"],
  },
  {
    name: "PDF Tools",
    description:
      "Un ensemble d'outils permettant la modification de PDF (Joindre, Diviser, Réorganiser, etc.). Après traitement, aucun fichier n'est conservé sur le serveur.",
    type: "Jeu",
    url: "https://pdf.nicolas.guerroudj.fr",
    src: "//github.com/NicolasGdj/PdfTools/",
    image: "pdftools.webp",
    year: 2024,
    tags: ["NodeJS", "EJS", "i18n"],
  },
];
