module.exports = [
  {
    name: "Bombparty",
    description:
      "Jeu multijoueur où chaque participant doit trouver un mot contenant une suite de lettres prédéfinie.",
    type: "Application Web",
    url: "http://www.bombparty.nicolas.guerroudj.fr",
    src: "//github.com/NicolasGdj/Bombparty",
    image: "bombparty.png",
    year: 2020,
    tags: ["NodeJS", "Socket IO"],
  },
  {
    name: "MyLimits",
    description: "Carte de la France présentant la limitation de 100 km autour de sa position.",
    type: "Application Web",
    url: "http://mylimits.nicolas.guerroudj.fr",
    src: "//github.com/NicolasGdj/MyLimits",
    image: "mylimits.png",
    year: 2020,
    tags: ["NodeJS", "Google API"],
  },
  {
    name: "DrawIt",
    description:
      "Jeu multijoueur où chaque participant doit trouver le mot dessiné par un autre participant.",
    type: "Application Web",
    url: "http://drawit.nicolas.guerroudj.fr",
    src: "//github.com/NicolasGdj/drawit",
    image: "drawit.png",
    year: 2020,
    tags: ["NodeJS", "Socket IO"],
  },
  {
    name: "GladOS",
    description: "Système d'exploitation dont le shell est inspiré de Glados du jeu Portal",
    type: "Système d'exploitation",
    url: "",
    src: "//github.com/NicolasGdj/GladOS",
    image: "glados.png",
    year: 2022,
    tags: ["C"],
  },
  {
    name: "TwoNotes",
    description: "Application mobile permettant la prise de note collaborative",
    type: "Application Mobile",
    src: "//github.com/NicolasGdj/TwoNotes",
    image: "twonotes.png",
    year: 2022,
    tags: ["React Native"],
  },
  {
    name: "CV",
    description:
      "Le site web sur lequel vous vous trouvez actuellement, présentant mon curriculum vitae ainsi que mes projets personnels.",
    type: "Application Web",
    url: "https://nicolas.guerroudj.fr",
    src: "//github.com/NicolasGdj/CV",
    image: "cv.png",
    year: 2023,
    tags: ["NodeJS", "EJS"],
  },
  {
    name: "Chromalight",
    description:
      "Un jeu de puzzle basé sur les lasers, où les joueurs doivent dévier les rayons à l'aide de miroirs pour résoudre les enigmes.",
    type: "Jeu",
    url: "https://nicolasgdj.github.io/Chromalight/WebGL/",
    src: "//github.com/NicolasGdj/Chromalight/",
    image: "chromalight.png",
    year: 2023,
    tags: ["C#", "Unity"],
  },
];
